name: CI

# Run this workflow every time a commit gets pushed to main
on:
  push:
    branches:
      - main
  #pull_request:
  #  branches: 
  #    - main

jobs:
    build:
        name: Call OneBranch ADO Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://identitydivision.visualstudio.com/IDDP/OneBranch
            azure-pipeline-name: 'MSAL.NET-OneBranch/MSAL.NET-OneBranch-CI-Official'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
